### ISSUE TITLE
stop adding recolors

### ISSUE THREAD

**Issue by tobyplowy** [Gerold55/MineClone-2-Textures#11]
@kingoscargames please STOP adding recolors of pixelperfection textures
we need to make uniqe textures if poeple whant pixelperfection than they just have to download pixel perfection and not this pack

**Comment by Gerold55** [comment]
We all need to be on same page here I like @kingoscargames textures but we all need to keep same consistency so we have a darn good texture pack

**Comment by tobyplowy** [comment]
@Gerold55 whatever the art style is we should not use textures from Pixelperfection (or any other pack) 
so we stay Unique That's not to say that you can't use them as Inspiration

Also @kingoscargames ik spreek ook Nederlands maar ik ben en Belg XD
Ik wilde dat gewoon zeggen XD

**Comment by Gerold55** [comment]
Yeah

**Comment by kingoscargames** [comment]
Ok.

**Comment by kingoscargames** [comment]
> @kingoscargames please STOP adding recolors of pixelperfection textures

Im making new "TNT" textures that arent recolored :D

> Also @kingoscargames ik spreek ook Nederlands maar ik ben en Belg XD
Ik wilde dat gewoon zeggen XD

Ik wist dat al.

**Comment by Gerold55** [comment]
Have fixed recoloring issues
